"""initial_schema — single squashed baseline for the v1.0 release.

Generated from the SQLAlchemy models (LUXSWIRL-178): the pre-release migration
chain (000_v1_0_baseline .. 005_reconcile_with_models) was collapsed into this
one "fresh build" baseline. TimescaleDB hypertable/retention/continuous-aggregate
DDL is NOT here — the app applies it at boot (timescale_*). `make migration-check`
asserts this baseline matches the models (alembic check clean).

Revision ID: 43a72b7c97c8
Revises:
Create Date: 2026-06-19

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.encrypted_types  # EncryptedString / EncryptedJSON column types

# revision identifiers, used by Alembic.
revision = '43a72b7c97c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_name', sa.String(length=255), nullable=True, comment='Friendly name for the agent (editable, set during approval)'),
    sa.Column('agent_run_id', sa.String(length=255), nullable=True, comment='Current run ID (UUID), changes on agent restart'),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default='NOW()', nullable=False, comment='Timestamp when agent was first seen'),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default='NOW()', nullable=False, comment='Timestamp when agent last reported'),
    sa.Column('hostname', sa.String(length=255), nullable=True, comment='Agent hostname'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Agent IP address'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Agent version'),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='Tags for grouping/filtering agents'),
    sa.Column('status', sa.Enum('online', 'degraded', 'offline', 'unknown', name='agentstatus', native_enum=False, length=20), server_default='unknown', nullable=True, comment='Agent status: online, degraded, offline, unknown'),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True, comment='Agent uptime in seconds (from last heartbeat)'),
    sa.Column('checks_total', sa.Integer(), server_default='0', nullable=True, comment='Total number of checks configured'),
    sa.Column('checks_active', sa.Integer(), server_default='0', nullable=True, comment='Number of checks currently running'),
    sa.Column('checks_executed_total', sa.Integer(), server_default='0', nullable=True, comment='Total checks executed since agent start'),
    sa.Column('checks_succeeded_total', sa.Integer(), server_default='0', nullable=True, comment='Total successful checks since agent start'),
    sa.Column('checks_failed_total', sa.Integer(), server_default='0', nullable=True, comment='Total failed checks since agent start'),
    sa.Column('cpu_percent', sa.Float(), nullable=True, comment='CPU usage percentage'),
    sa.Column('memory_mb', sa.Integer(), nullable=True, comment='Memory usage in MB'),
    sa.Column('queue_depth', sa.Integer(), server_default='0', nullable=True, comment='Current result queue depth'),
    sa.Column('last_error', sa.String(length=1000), nullable=True, comment='Last error message'),
    sa.Column('server_unreachable_count', sa.Integer(), server_default='0', nullable=True, comment='Number of failed server connection attempts'),
    sa.Column('stored_reports_count', sa.Integer(), server_default='0', nullable=True, comment='Number of stored reports waiting to send'),
    sa.Column('stored_reports_oldest_timestamp', sa.Float(), nullable=True, comment='Timestamp of oldest stored report'),
    sa.Column('open_file_descriptors', sa.Integer(), nullable=True, comment='Number of open file descriptors'),
    sa.Column('fd_limit_soft', sa.Integer(), nullable=True, comment='Soft limit for file descriptors (ulimit)'),
    sa.Column('fd_usage_percent', sa.Float(), nullable=True, comment='FD usage percentage vs soft limit'),
    sa.Column('subprocess_count', sa.Integer(), nullable=True, comment='Number of child subprocesses'),
    sa.Column('config_version', sa.String(length=50), nullable=True, comment='Last known config version from agent'),
    sa.Column('checks_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when checks were last modified (for config change detection)'),
    sa.Column('heartbeat_interval', sa.Integer(), nullable=True, comment='Heartbeat interval in seconds (NULL = use global default)'),
    sa.Column('check_sync_interval', sa.Integer(), nullable=True, comment='Check sync interval in seconds (NULL = use global default)'),
    sa.Column('report_interval', sa.Integer(), nullable=True, comment='Reporter batch send interval in seconds (NULL = use global default)'),
    sa.Column('report_batch_size', sa.Integer(), nullable=True, comment='Reporter batch size in results (NULL = use global default)'),
    sa.Column('report_max_files_per_batch', sa.Integer(), nullable=True, comment='Max stored reports to process per batch (NULL = use global default)'),
    sa.Column('report_process_interval', sa.Integer(), nullable=True, comment='Interval for processing stored reports in seconds (NULL = use global default)'),
    sa.Column('report_max_queue_size', sa.Integer(), nullable=True, comment='Maximum results queue size (NULL = use global default)'),
    sa.Column('report_backpressure_threshold', sa.Float(), nullable=True, comment='Backpressure threshold 0.0-1.0 (NULL = use global default)'),
    sa.Column('max_concurrent_checks', sa.Integer(), nullable=True, comment='Maximum concurrent checks (NULL = use global default)'),
    sa.Column('watchdog_interval', sa.Integer(), nullable=True, comment='Watchdog check interval in seconds (NULL = use global default)'),
    sa.Column('watchdog_stall_threshold', sa.Integer(), nullable=True, comment='Watchdog stall threshold count (NULL = use global default)'),
    sa.Column('log_level', sa.String(length=20), nullable=True, comment='Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL (NULL = use global default)'),
    sa.Column('approval_status', sa.Enum('pending', 'active', 'paused', 'disabled', 'rejected', name='agentapprovalstatus', native_enum=False, length=20), server_default='pending', nullable=False, comment='Approval status: pending, active, paused, disabled, rejected'),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True, comment='Bcrypt hash of agent-specific API key (NULL until approved)'),
    sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True, comment='When the API key was created/last regenerated'),
    sa.Column('api_key_last_used', sa.DateTime(timezone=True), nullable=True, comment='When the API key was last used for authentication'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='When the agent was approved by admin'),
    sa.Column('approved_by', sa.String(length=255), nullable=True, comment='Admin user who approved the agent (future use)'),
    sa.Column('status_reason', sa.String(length=500), nullable=True, comment='Reason for paused/disabled/rejected status'),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True, comment='When the approval_status was last changed'),
    sa.Column('status_changed_by', sa.String(length=255), nullable=True, comment='Admin user who changed the status (future use)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_agent_name', 'agents', ['agent_name'], unique=False)
    op.create_index('idx_agents_last_seen', 'agents', ['last_seen'], unique=False)
    op.create_index(op.f('ix_agents_agent_name'), 'agents', ['agent_name'], unique=True)
    op.create_table('alerts',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the alert rule'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what this alert does'),
    sa.Column('trigger_type', sa.Enum('status_change', 'threshold', 'repeated_failure', 'ssl_cert_expiry', name='alerttriggertype', native_enum=False, length=50), nullable=False, comment='Type of trigger (status_change, threshold, repeated_failure, ssl_cert_expiry)'),
    sa.Column('trigger_config', sa.JSON(), nullable=False, comment='Trigger-specific configuration (JSONB for flexibility)'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether this alert is active'),
    sa.Column('is_global', sa.Boolean(), server_default='false', nullable=False, comment='Whether this is a global alert (applies to filtered checks) or per-check'),
    sa.Column('notify_on_recovery', sa.Boolean(), server_default='true', nullable=False, comment='Send notification when service recovers (comes back up)'),
    sa.Column('resend_interval_minutes', sa.Integer(), nullable=True, comment="Resend notification after X minutes if still down (NULL = don't resend)"),
    sa.Column('max_resends', sa.Integer(), nullable=True, comment='Maximum number of resends (NULL = unlimited)'),
    sa.Column('custom_subject', sa.String(length=500), nullable=True, comment='Custom subject line template (leave blank for default)'),
    sa.Column('custom_message', sa.Text(), nullable=True, comment='Custom message body template (leave blank for default)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (NULL if active)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_deleted', 'alerts', ['deleted_at'], unique=False)
    op.create_index('idx_alerts_enabled', 'alerts', ['is_enabled'], unique=False)
    op.create_index('idx_alerts_trigger_type', 'alerts', ['trigger_type'], unique=False)
    op.create_table('job_configurations',
    sa.Column('job_key', sa.String(length=191), nullable=False, comment='Unique job identifier'),
    sa.Column('function_name', sa.String(length=100), nullable=False, comment='Python function name to execute'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Human-readable job name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Job description'),
    sa.Column('category', sa.Enum('cleanup', 'monitoring', 'system', name='schedulerjobcategory', native_enum=False, length=50), nullable=False, comment='Job category (cleanup, monitoring, system)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether job is enabled'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parameters passed to job function'),
    sa.Column('trigger_type', sa.Enum('interval', 'cron', 'manual', name='schedulertriggertype', native_enum=False, length=20), nullable=False, comment='Trigger type: interval, cron, manual'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='Interval in seconds (for interval triggers)'),
    sa.Column('cron_expression', sa.String(length=100), nullable=True, comment='Cron expression (for cron triggers)'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='Timezone for cron expressions'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='When job should next run'),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=False, comment='Maximum execution time before timeout'),
    sa.Column('jitter_ms', sa.Integer(), nullable=False, comment='Random jitter in milliseconds to spread load'),
    sa.Column('lease_token', sa.Uuid(), nullable=True, comment='Current lease token (UUID)'),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True, comment='When current lease expires'),
    sa.Column('retry_limit', sa.Integer(), nullable=False, comment='Max retries before auto-disable (0=infinite)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Current consecutive failure count'),
    sa.Column('backoff_seconds', sa.Integer(), nullable=False, comment='Base backoff time for exponential retry'),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=False, comment='Log warning on failure'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='When job last ran'),
    sa.Column('last_status', sa.Enum('running', 'success', 'warning', 'failed', name='schedulerexecutionstatus', native_enum=False, length=20), nullable=True, comment='Last execution status'),
    sa.Column('total_runs', sa.Integer(), nullable=False, comment='Total successful runs'),
    sa.Column('failed_runs', sa.Integer(), nullable=False, comment='Total failed runs'),
    sa.Column('average_duration', sa.Float(), nullable=True, comment='Average execution duration in seconds'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key')
    )
    op.create_index('idx_job_configurations_enabled', 'job_configurations', ['enabled'], unique=False)
    op.create_index('idx_job_configurations_lease', 'job_configurations', ['lease_expires_at'], unique=False)
    op.create_index('idx_job_configurations_next_run', 'job_configurations', ['next_run_at'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Execution UUID'),
    sa.Column('job_key', sa.String(length=191), nullable=False, comment='Job identifier'),
    sa.Column('job_name', sa.String(length=200), nullable=False, comment='Job display name at time of execution'),
    sa.Column('category', sa.Enum('cleanup', 'monitoring', 'system', name='schedulerjobcategory', native_enum=False, length=50), nullable=True, comment='Job category at time of execution'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When execution completed'),
    sa.Column('status', sa.Enum('running', 'success', 'warning', 'failed', name='schedulerexecutionstatus', native_enum=False, length=20), nullable=False, comment='Execution status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Job output/result data'),
    sa.Column('records_processed', sa.Integer(), nullable=True, comment='Number of records processed'),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='Execution duration in seconds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_executions_job_key', 'job_executions', ['job_key'], unique=False)
    op.create_index('idx_job_executions_started_at', 'job_executions', ['started_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Job UUID'),
    sa.Column('job_type', sa.Enum('network_scan', 'network_discover', name='jobtype', native_enum=False, length=50), nullable=False, comment='Type of job (network_scan, port_scan, etc.)'),
    sa.Column('agent_id', sa.Uuid(), nullable=True, comment='Agent to run job on (NULL = run on server)'),
    sa.Column('params', sa.JSON(), nullable=False, comment='Job-specific parameters (JSON)'),
    sa.Column('status', sa.Enum('pending', 'assigned', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=20), nullable=False, comment='Job status (pending/assigned/running/completed/failed/cancelled)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Job priority (higher = runs first)'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True, comment='When job was assigned to agent'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When job execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When job execution completed'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When to auto-purge this job (created_at + retention_days)'),
    sa.Column('result', sa.JSON(), nullable=True, comment='Job result data (JSON)'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message if job failed'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User who created this job'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Tags for organizing/filtering jobs (JSON array)'),
    sa.Column('schedule', sa.JSON(), nullable=True, comment='Scheduling config (NULL = one-time job)'),
    sa.Column('automation_config', sa.JSON(), nullable=True, comment='Automation rules (NULL = manual processing)'),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True, comment='Parent job ID for recurring job instances'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_agent_status_priority', 'jobs', ['agent_id', 'status', 'priority'], unique=False, postgresql_where=sa.text("status IN ('pending', 'assigned')"))
    op.create_index('idx_jobs_expires_status', 'jobs', ['expires_at', 'status'], unique=False, postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"))
    op.create_index('idx_jobs_type_status', 'jobs', ['job_type', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_agent_id'), 'jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_jobs_expires_at'), 'jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('maintenance_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('agent_delete', 'bulk_check_delete', 'bulk_check_toggle', 'bulk_check_modify', 'bulk_check_import', 'bulk_check_create', 'status_page_delete', name='maintenancejobkind', native_enum=False, length=50), nullable=False, comment='MaintenanceJobKind value (agent_delete, bulk_check_delete, etc.)'),
    sa.Column('target_id', sa.Uuid(), nullable=True, comment='Primary entity being mutated (agent_id, status_page_id, etc.)'),
    sa.Column('params', sa.JSON(), nullable=False, comment='Kind-specific args (check_ids list, URL list, etc.)'),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='maintenancejobstatus', native_enum=False, length=20), nullable=False, comment='MaintenanceJobStatus value (queued, running, done, failed)'),
    sa.Column('owner_id', sa.Uuid(), nullable=True, comment='User who initiated this job (audit trail)'),
    sa.Column('progress', sa.JSON(), nullable=True, comment='Optional partial-progress payload (processed/total/message)'),
    sa.Column('error', sa.Text(), nullable=True, comment="Failure reason when status='failed'"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maint_jobs_status_created', 'maintenance_jobs', ['status', 'created_at'], unique=False)
    op.create_index('uq_maint_jobs_inflight', 'maintenance_jobs', ['kind', 'target_id'], unique=True, postgresql_where="status IN ('queued', 'running')")
    op.create_table('notification_providers',
    sa.Column('provider_type', sa.Enum('email', 'webhook', 'homeassistant', name='notificationprovidertype', native_enum=False, length=50), nullable=False, comment='Type of notification provider (email, webhook, homeassistant, etc.)'),
    sa.Column('friendly_name', sa.String(length=255), nullable=False, comment="User-friendly name for this provider instance (e.g., 'Google SMTP', 'PagerDuty')"),
    sa.Column('config', sa.JSON(), nullable=False, comment='Provider-specific configuration (JSONB for flexibility)'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether this provider is enabled (can send notifications)'),
    sa.Column('is_default_enabled', sa.Boolean(), server_default='false', nullable=False, comment='Whether this provider is enabled by default for new checks'),
    sa.Column('rate_limit_count', sa.Integer(), nullable=True, comment='Maximum notifications per rate_limit_window_minutes (NULL = no limit)'),
    sa.Column('rate_limit_window_minutes', sa.Integer(), server_default='60', nullable=True, comment='Time window for rate limiting in minutes'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (NULL if active)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_providers_deleted', 'notification_providers', ['deleted_at'], unique=False)
    op.create_index('idx_notification_providers_type', 'notification_providers', ['provider_type'], unique=False)
    op.create_table('registration_keys',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name/description for this registration key'),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='Bcrypt hash of the registration key'),
    sa.Column('description', sa.Text(), nullable=True, comment="Optional notes about this key's purpose"),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='Admin user who created this key (future use)'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='When this key was last used for authentication'),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False, comment='Number of times this key has been used'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When this key was revoked (NULL = active)'),
    sa.Column('revoked_by', sa.String(length=255), nullable=True, comment='Admin user who revoked this key (future use)'),
    sa.Column('revoked_reason', sa.String(length=500), nullable=True, comment='Reason for revocation'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registration_keys_last_used_at', 'registration_keys', ['last_used_at'], unique=False)
    op.create_index('idx_registration_keys_revoked_at', 'registration_keys', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_registration_keys_key_hash'), 'registration_keys', ['key_hash'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False, comment="Unique setting key (e.g., 'check.default_interval')"),
    sa.Column('category', sa.Enum('check', 'alert', 'system', 'job', 'metrics', 'database', 'general', 'security', name='settingcategory', native_enum=False, length=50), nullable=False, comment='Setting category (check, alert, system, job, database, general, metrics, security)'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='Optional subcategory for grouping settings within a category'),
    sa.Column('value', sa.JSON(), nullable=False, comment='Setting value (JSONB: {value: <actual>, type: <type>})'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Human-readable display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what this setting controls'),
    sa.Column('default_value', sa.JSON(), nullable=False, comment='System default value (for reset functionality)'),
    sa.Column('validation', sa.JSON(), nullable=True, comment='Validation rules (min, max, enum, etc.)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('key', name='uq_settings_key')
    )
    op.create_index('idx_settings_category', 'settings', ['category'], unique=False)
    op.create_index('idx_settings_key', 'settings', ['key'], unique=False)
    op.create_index('idx_settings_subcategory', 'settings', ['subcategory'], unique=False)
    op.create_table('status_pages',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name of the status page'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly slug for public access (e.g., /status/production)'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Optional description of the status page'),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False, comment='Whether the status page is publicly accessible'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Display configuration (theme, show_uptime, etc.)'),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Ordered array of items to display (checks and groups)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_status_page_slug')
    )
    op.create_index('idx_status_pages_is_public', 'status_pages', ['is_public'], unique=False)
    op.create_index('idx_status_pages_slug', 'status_pages', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False, comment='Username for login (unique)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt password hash'),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='userrole', native_enum=False, length=20), server_default='viewer', nullable=False, comment='User role: admin, editor, viewer'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether user account is active'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Full name of user'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='When password was last changed'),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='Count of consecutive failed login attempts (reset on success)'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this timestamp (NULL = not locked)'),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False, comment='Whether user must change password on next login'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Username of admin who created this user'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_metrics',
    sa.Column('agent_id', sa.Uuid(), nullable=False, comment='Reference to agent (UUID)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Metric timestamp'),
    sa.Column('cpu_percent', sa.Float(), nullable=True, comment='CPU usage percentage'),
    sa.Column('memory_mb', sa.Integer(), nullable=True, comment='Memory usage in MB'),
    sa.Column('queue_depth', sa.Integer(), nullable=True, comment='Result queue depth'),
    sa.Column('queue_max_size', sa.Integer(), nullable=True, comment='Max queue size since last heartbeat'),
    sa.Column('checks_executed', sa.Integer(), nullable=True, comment='Checks executed since last heartbeat'),
    sa.Column('checks_succeeded', sa.Integer(), nullable=True, comment='Successful checks since last heartbeat'),
    sa.Column('checks_failed', sa.Integer(), nullable=True, comment='Failed checks since last heartbeat'),
    sa.Column('avg_check_duration_ms', sa.Float(), nullable=True, comment='Average check duration in milliseconds'),
    sa.Column('status', sa.Enum('online', 'degraded', 'offline', 'unknown', name='agentstatus', native_enum=False, length=20), nullable=True, comment='Agent status at this timestamp'),
    sa.Column('errors_count', sa.Integer(), server_default='0', nullable=True, comment='Error count since last heartbeat'),
    sa.Column('warnings_count', sa.Integer(), server_default='0', nullable=True, comment='Warning count since last heartbeat'),
    sa.Column('last_error', sa.String(length=1000), nullable=True, comment='Last error message'),
    sa.Column('open_file_descriptors', sa.Integer(), nullable=True, comment='Number of open file descriptors'),
    sa.Column('fd_limit_soft', sa.Integer(), nullable=True, comment='Soft limit for file descriptors'),
    sa.Column('fd_usage_percent', sa.Float(), nullable=True, comment='FD usage percentage vs soft limit'),
    sa.Column('subprocess_count', sa.Integer(), nullable=True, comment='Number of child subprocesses'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'timestamp'),
    comment='Time-series agent health metrics'
    )
    op.create_index('idx_agent_metrics_agent_time', 'agent_metrics', ['agent_id', 'timestamp'], unique=False)
    op.create_table('alert_notification_mappings',
    sa.Column('alert_id', sa.Uuid(), nullable=False, comment='Foreign key to alerts table'),
    sa.Column('notification_provider_id', sa.Uuid(), nullable=False, comment='Foreign key to notification_providers table'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether this specific alert-provider mapping is enabled'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_provider_id'], ['notification_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'notification_provider_id', name='uq_alert_notification')
    )
    op.create_index('idx_alert_notification_alert', 'alert_notification_mappings', ['alert_id'], unique=False)
    op.create_index('idx_alert_notification_provider', 'alert_notification_mappings', ['notification_provider_id'], unique=False)
    op.create_table('checks',
    sa.Column('agent_id', sa.Uuid(), nullable=False, comment='Foreign key to agents table (UUID)'),
    sa.Column('depends_on_check_id', sa.Uuid(), nullable=True, comment='Parent check this one depends on; notifications suppressed when parent is down'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Friendly display name for the check (editable)'),
    sa.Column('check_type', sa.Enum('ping', 'http', 'tcp', 'json', 'dns', 'mysql', 'postgres', 'synthetic', name='checktype', native_enum=False, length=50), nullable=False, comment='Type of check (ping, http, tcp, json, etc.)'),
    sa.Column('target', app.core.encrypted_types.EncryptedString(length=1000), nullable=False, comment='Target of the check (URL, hostname, IP, etc.) - encrypted at rest'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='How often check runs (in seconds)'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='Check timeout (in seconds)'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Human-readable description of the check'),
    sa.Column('check_config', app.core.encrypted_types.EncryptedJSON(), nullable=True, comment='Check-type-specific configuration - encrypted at rest (may contain sensitive data)'),
    sa.Column('retry_attempts', sa.Integer(), server_default='2', nullable=True, comment='Number of retry attempts for a single check execution before marking as failed'),
    sa.Column('retry_interval_seconds', sa.Integer(), server_default='30', nullable=False, comment='Retry interval in seconds (Heartbeat Retry Interval)'),
    sa.Column('resend_notification_after', sa.Integer(), nullable=True, comment='Resend notification if down X times consecutively (NULL = disabled)'),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='Tags for organizing/filtering checks'),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether check is enabled'),
    sa.Column('assignment_mode', sa.Enum('manual', 'replicate', 'distribute', name='assignmentmode', native_enum=False, length=20), server_default='manual', nullable=False, comment='Assignment mode: manual, replicate, distribute'),
    sa.Column('agent_selector', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Agent selector for replicate/distribute modes (JSON: {tags: [...]} or {agent_ids: [...]})'),
    sa.Column('script_code', sa.Text(), nullable=True, comment='Python script code for synthetic checks (Playwright async)'),
    sa.Column('connection_string_encrypted', app.core.encrypted_types.EncryptedString(length=1000), nullable=True, comment='Encrypted database connection string (automatically encrypted at rest)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_check_id'], ['checks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checks_agent_id', 'checks', ['agent_id'], unique=False)
    op.create_index('idx_checks_depends_on_check_id', 'checks', ['depends_on_check_id'], unique=False)
    op.create_index('idx_checks_type', 'checks', ['check_type'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('alert_id', sa.Uuid(), nullable=False, comment='Foreign key to alerts table'),
    sa.Column('notification_provider_id', sa.Uuid(), nullable=False, comment='Foreign key to notification_providers table'),
    sa.Column('check_result_id', sa.Uuid(), nullable=False, comment='Check result ID (reference only, no FK for TimescaleDB compression)'),
    sa.Column('check_result_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Check result timestamp (reference only, no FK for TimescaleDB compression)'),
    sa.Column('check_id', sa.Uuid(), nullable=True, comment='Check ID (denormalized — avoids join through check_results to reach checks)'),
    sa.Column('check_success', sa.Boolean(), nullable=True, comment='Whether the check passed (denormalized from check_results)'),
    sa.Column('check_latency_ms', sa.Float(), nullable=True, comment='Check latency in ms (denormalized from check_results)'),
    sa.Column('status', sa.Enum('sent', 'failed', 'retrying', 'rate_limited', 'deduplicated', 'suppressed', name='notificationstatus', native_enum=False, length=50), nullable=False, comment='Status of notification (sent, failed, retrying, rate_limited, deduplicated, suppressed)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if notification failed'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When notification was sent'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='Provider-specific response data (JSONB)'),
    sa.Column('notification_hash', sa.String(length=64), nullable=True, comment='Hash of notification content for de-duplication'),
    sa.Column('is_resend', sa.Boolean(), server_default='false', nullable=False, comment='Whether this is a resend of a previous notification'),
    sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False, comment='How many times this notification has been resent'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_provider_id'], ['notification_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_logs_alert', 'notification_logs', ['alert_id'], unique=False)
    op.create_index('idx_notification_logs_check_result', 'notification_logs', ['check_result_id', 'check_result_timestamp'], unique=False)
    op.create_index('idx_notification_logs_provider', 'notification_logs', ['notification_provider_id'], unique=False)
    op.create_index('idx_notification_logs_provider_sent', 'notification_logs', ['notification_provider_id', 'sent_at'], unique=False)
    op.create_index('idx_notification_logs_sent_at', 'notification_logs', ['sent_at'], unique=False)
    op.create_index('idx_notification_logs_status', 'notification_logs', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Foreign key to users table (UUID)'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of session token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this session expires'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address from which session was created'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent string from session creation'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last activity on this session (for idle timeout)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_last_activity', 'sessions', ['last_activity_at'], unique=False)
    op.create_index('idx_sessions_token_hash', 'sessions', ['token_hash'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_last_activity_at'), 'sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('alert_check_mappings',
    sa.Column('alert_id', sa.Uuid(), nullable=False, comment='Foreign key to alerts table'),
    sa.Column('check_id', sa.Uuid(), nullable=False, comment='Foreign key to checks table (UUID)'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Whether this specific alert-check mapping is enabled'),
    sa.Column('override_resend_interval', sa.Integer(), nullable=True, comment='Override resend interval for this specific check (minutes)'),
    sa.Column('override_max_resends', sa.Integer(), nullable=True, comment='Override max resends for this specific check'),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True, comment='Notifications for this alert-check relationship are snoozed until this timestamp - NULL means not snoozed'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'check_id', name='uq_alert_check')
    )
    op.create_index('idx_alert_check_alert', 'alert_check_mappings', ['alert_id'], unique=False)
    op.create_index('idx_alert_check_check', 'alert_check_mappings', ['check_id'], unique=False)
    op.create_table('check_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key (part of composite PK with created_at)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when artifact was created (part of composite PK for TimescaleDB)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('check_id', sa.Uuid(), nullable=False, comment='Check that generated this artifact'),
    sa.Column('check_result_id', sa.Uuid(), nullable=False, comment='Check result ID (reference only, no FK for TimescaleDB compression)'),
    sa.Column('check_result_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Check result timestamp (reference only, no FK for TimescaleDB compression)'),
    sa.Column('artifact_type', sa.Enum('screenshot', 'trace', 'video', 'har', name='checkartifacttype', native_enum=False, length=20), nullable=False, comment='Type: screenshot, trace, video, har'),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='MIME type: image/png, application/zip, etc'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename for download'),
    sa.Column('size_bytes', sa.Integer(), nullable=False, comment='Size of binary data in bytes'),
    sa.Column('data', sa.LargeBinary(), nullable=False, comment='Binary artifact data'),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index('idx_check_artifacts_check_id', 'check_artifacts', ['check_id'], unique=False)
    op.create_index('idx_check_artifacts_created', 'check_artifacts', ['created_at'], unique=False)
    op.create_index('idx_check_artifacts_result_id', 'check_artifacts', ['check_result_id', 'check_result_timestamp'], unique=False)
    op.create_index('idx_check_artifacts_type', 'check_artifacts', ['artifact_type'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Result UUID (generated by agent before execution)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the check was executed'),
    sa.Column('agent_id', sa.Uuid(), nullable=False, comment='Foreign key to agents table (UUID)'),
    sa.Column('check_id', sa.Uuid(), nullable=False, comment='Foreign key to checks table (UUID)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the check succeeded'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='Check latency in milliseconds'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message if check failed'),
    sa.Column('error_type', sa.Enum('timeout_error', 'connection_error', 'database_error', 'query_error', 'authentication_error', 'unknown_error', name='checkerrortype', native_enum=False, length=100), nullable=True, comment='Error category emitted by the agent (timeout_error, connection_error, …)'),
    sa.Column('http_status_code', sa.Integer(), nullable=True, comment='HTTP status code (for HTTP checks)'),
    sa.Column('http_response_time_ms', sa.Float(), nullable=True, comment='HTTP response time in milliseconds'),
    sa.Column('metrics', sa.Text(), nullable=True, comment='Additional metrics as JSON string'),
    sa.Column('response_data', sa.Text(), nullable=True, comment='Response body or data (truncated if large)'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_latency_non_negative'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('idx_check_results_agent_check_timestamp', 'check_results', ['agent_id', 'check_id', 'timestamp'], unique=False)
    op.create_index('idx_check_results_agent_timestamp', 'check_results', ['agent_id', 'timestamp'], unique=False)
    op.create_index('idx_check_results_id', 'check_results', ['id'], unique=False)
    op.create_index('idx_check_results_success', 'check_results', ['success'], unique=False)
    op.create_index('idx_check_results_timestamp', 'check_results', ['timestamp'], unique=False)
    op.create_index('uq_check_results_check_ts', 'check_results', ['check_id', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_check_results_check_ts', table_name='check_results')
    op.drop_index('idx_check_results_timestamp', table_name='check_results')
    op.drop_index('idx_check_results_success', table_name='check_results')
    op.drop_index('idx_check_results_id', table_name='check_results')
    op.drop_index('idx_check_results_agent_timestamp', table_name='check_results')
    op.drop_index('idx_check_results_agent_check_timestamp', table_name='check_results')
    op.drop_table('check_results')
    op.drop_index('idx_check_artifacts_type', table_name='check_artifacts')
    op.drop_index('idx_check_artifacts_result_id', table_name='check_artifacts')
    op.drop_index('idx_check_artifacts_created', table_name='check_artifacts')
    op.drop_index('idx_check_artifacts_check_id', table_name='check_artifacts')
    op.drop_table('check_artifacts')
    op.drop_index('idx_alert_check_check', table_name='alert_check_mappings')
    op.drop_index('idx_alert_check_alert', table_name='alert_check_mappings')
    op.drop_table('alert_check_mappings')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_activity_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_token_hash', table_name='sessions')
    op.drop_index('idx_sessions_last_activity', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_notification_logs_status', table_name='notification_logs')
    op.drop_index('idx_notification_logs_sent_at', table_name='notification_logs')
    op.drop_index('idx_notification_logs_provider_sent', table_name='notification_logs')
    op.drop_index('idx_notification_logs_provider', table_name='notification_logs')
    op.drop_index('idx_notification_logs_check_result', table_name='notification_logs')
    op.drop_index('idx_notification_logs_alert', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('idx_checks_type', table_name='checks')
    op.drop_index('idx_checks_depends_on_check_id', table_name='checks')
    op.drop_index('idx_checks_agent_id', table_name='checks')
    op.drop_table('checks')
    op.drop_index('idx_alert_notification_provider', table_name='alert_notification_mappings')
    op.drop_index('idx_alert_notification_alert', table_name='alert_notification_mappings')
    op.drop_table('alert_notification_mappings')
    op.drop_index('idx_agent_metrics_agent_time', table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_status_pages_slug', table_name='status_pages')
    op.drop_index('idx_status_pages_is_public', table_name='status_pages')
    op.drop_table('status_pages')
    op.drop_index('idx_settings_subcategory', table_name='settings')
    op.drop_index('idx_settings_key', table_name='settings')
    op.drop_index('idx_settings_category', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_registration_keys_key_hash'), table_name='registration_keys')
    op.drop_index('idx_registration_keys_revoked_at', table_name='registration_keys')
    op.drop_index('idx_registration_keys_last_used_at', table_name='registration_keys')
    op.drop_table('registration_keys')
    op.drop_index('idx_notification_providers_type', table_name='notification_providers')
    op.drop_index('idx_notification_providers_deleted', table_name='notification_providers')
    op.drop_table('notification_providers')
    op.drop_index('uq_maint_jobs_inflight', table_name='maintenance_jobs', postgresql_where="status IN ('queued', 'running')")
    op.drop_index('idx_maint_jobs_status_created', table_name='maintenance_jobs')
    op.drop_table('maintenance_jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_expires_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_agent_id'), table_name='jobs')
    op.drop_index('idx_jobs_type_status', table_name='jobs')
    op.drop_index('idx_jobs_expires_status', table_name='jobs', postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"))
    op.drop_index('idx_jobs_agent_status_priority', table_name='jobs', postgresql_where=sa.text("status IN ('pending', 'assigned')"))
    op.drop_table('jobs')
    op.drop_index('idx_job_executions_started_at', table_name='job_executions')
    op.drop_index('idx_job_executions_job_key', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('idx_job_configurations_next_run', table_name='job_configurations')
    op.drop_index('idx_job_configurations_lease', table_name='job_configurations')
    op.drop_index('idx_job_configurations_enabled', table_name='job_configurations')
    op.drop_table('job_configurations')
    op.drop_index('idx_alerts_trigger_type', table_name='alerts')
    op.drop_index('idx_alerts_enabled', table_name='alerts')
    op.drop_index('idx_alerts_deleted', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agents_agent_name'), table_name='agents')
    op.drop_index('idx_agents_last_seen', table_name='agents')
    op.drop_index('idx_agents_agent_name', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###