"""Single source of truth for LuxSwirl's seeded default settings.

This module defines :data:`DEFAULT_SETTINGS`, the canonical list of default
application settings. It is seeded into the ``settings`` table by
``SettingsCoreService.ensure_default_settings``.

This data was faithfully merged from the two historical seed locations:

* ``app/db/database.py`` -> ``_init_default_settings()`` (check, alert, system,
  job, database categories, plus the general/security scaffolding).
* ``app/services/core/settings_core_service.py`` -> ``ensure_security_defaults``,
  ``ensure_general_defaults``, ``ensure_metrics_defaults`` (the live security,
  general, and metrics categories).

Each entry stores ``value`` raw and ``type`` separately; the seeder is
responsible for wrapping them into the column shape
``{"value": value, "type": type}``.

This is pure data — no logic lives here.
"""

from typing import Any

DEFAULT_SETTINGS: list[dict[str, Any]] = [
    # ------------------------------------------------------------------
    # check  (source: app/db/database.py)
    # ------------------------------------------------------------------
    {
        "key": "check.default_interval",
        "category": "check",
        "subcategory": None,
        "value": 60,
        "type": "int",
        "display_name": "Default Check Interval",
        "description": "Default interval in seconds between check executions",
        "validation": {"min": 10, "max": 86400},
    },
    {
        "key": "check.default_timeout",
        "category": "check",
        "subcategory": None,
        "value": 10,
        "type": "int",
        "display_name": "Default Timeout",
        "description": "Default timeout in seconds for check execution",
        "validation": {"min": 1, "max": 300},
    },
    {
        "key": "check.default_retry_attempts",
        "category": "check",
        "subcategory": None,
        "value": 2,
        "type": "int",
        "display_name": "Default Retry Attempts",
        "description": "Default number of retry attempts for a single check execution before marking as failed",
        "validation": {"min": 0, "max": 10},
    },
    {
        "key": "check.default_retry_interval",
        "category": "check",
        "subcategory": None,
        "value": 30,
        "type": "int",
        "display_name": "Default Retry Interval",
        "description": "Default wait time in seconds between retry attempts",
        "validation": {"min": 1, "max": 300},
    },
    {
        "key": "check.default_expected_status",
        "category": "check",
        "subcategory": None,
        "value": 200,
        "type": "int",
        "display_name": "Default Expected HTTP Status",
        "description": "Default expected HTTP status code for HTTP checks",
        "validation": {"min": 100, "max": 599},
    },
    {
        "key": "check.default_verify_ssl",
        "category": "check",
        "subcategory": None,
        "value": False,
        "type": "bool",
        "display_name": "Default Verify SSL",
        "description": "Default SSL certificate verification setting (false for self-signed certs)",
        "validation": None,
    },
    {
        "key": "check.default_http_method",
        "category": "check",
        "subcategory": None,
        "value": "GET",
        "type": "string",
        "display_name": "Default HTTP Method",
        "description": "Default HTTP method for HTTP checks",
        "validation": {"enum": ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]},
    },
    # ------------------------------------------------------------------
    # alert  (source: app/db/database.py)
    # ------------------------------------------------------------------
    {
        "key": "alert.default_consecutive_failures",
        "category": "alert",
        "subcategory": None,
        "value": 1,
        "type": "int",
        "display_name": "Default Consecutive Failures",
        "description": "Default number of consecutive failures before triggering alert",
        "validation": {"min": 1, "max": 100},
    },
    {
        "key": "alert.default_notify_on_recovery",
        "category": "alert",
        "subcategory": None,
        "value": True,
        "type": "bool",
        "display_name": "Default Notify on Recovery",
        "description": "Send notification when service recovers (comes back up)",
        "validation": None,
    },
    {
        "key": "alert.default_latency_threshold",
        "category": "alert",
        "subcategory": None,
        "value": 1000,
        "type": "int",
        "display_name": "Default Latency Threshold (ms)",
        "description": "Default latency threshold in milliseconds for threshold alerts",
        "validation": {"min": 1, "max": 60000},
    },
    {
        "key": "alert.ssl_cert_warning_days",
        "category": "alert",
        "subcategory": None,
        "value": 30,
        "type": "int",
        "display_name": "SSL Certificate Warning Days",
        "description": "Trigger warning when SSL certificate expires within this many days",
        "validation": {"min": 1, "max": 365},
    },
    {
        "key": "alert.ssl_cert_critical_days",
        "category": "alert",
        "subcategory": None,
        "value": 14,
        "type": "int",
        "display_name": "SSL Certificate Critical Days",
        "description": "Trigger critical alert when SSL certificate expires within this many days",
        "validation": {"min": 1, "max": 365},
    },
    # ------------------------------------------------------------------
    # system  (source: app/db/database.py)
    # ------------------------------------------------------------------
    {
        "key": "system.metrics_ttl_seconds",
        "category": "system",
        "subcategory": None,
        "value": 300,
        "type": "int",
        "display_name": "Metrics TTL (seconds)",
        "description": "How long to keep check results in metrics before considering them stale",
        "validation": {"min": 60, "max": 3600},
    },
    {
        "key": "system.max_history_points",
        "category": "system",
        "subcategory": None,
        "value": 1000,
        "type": "int",
        "display_name": "Max History Points",
        "description": "Maximum number of historical data points to return per check",
        "validation": {"min": 100, "max": 10000},
    },
    {
        "key": "system.agent_active_window_minutes",
        "category": "system",
        "subcategory": None,
        "value": 10,
        "type": "int",
        "display_name": "Agent Active Window (minutes)",
        "description": "Consider agent active if heartbeat seen within this many minutes",
        "validation": {"min": 1, "max": 60},
    },
    # ------------------------------------------------------------------
    # job  (source: app/db/database.py)
    # ------------------------------------------------------------------
    {
        "key": "job.default_timeout_seconds",
        "category": "job",
        "subcategory": None,
        "value": 300,
        "type": "int",
        "display_name": "Default Job Timeout (seconds)",
        "description": "Default timeout for job execution (5 minutes)",
        "validation": {"min": 10, "max": 3600},
    },
    {
        "key": "job.synthetic_timeout_seconds",
        "category": "job",
        "subcategory": None,
        "value": 600,
        "type": "int",
        "display_name": "Synthetic Job Timeout (seconds)",
        "description": "Timeout for synthetic monitoring jobs (10 minutes)",
        "validation": {"min": 60, "max": 1800},
    },
    {
        "key": "job.network_scan_timeout",
        "category": "job",
        "subcategory": None,
        "value": 10,
        "type": "int",
        "display_name": "Network Scan Timeout (seconds)",
        "description": "Timeout per host in network discovery scans",
        "validation": {"min": 1, "max": 60},
    },
    {
        "key": "job.network_scan_max_concurrent",
        "category": "job",
        "subcategory": None,
        "value": 100,
        "type": "int",
        "display_name": "Network Scan Max Concurrent",
        "description": "Maximum number of parallel host scans during network discovery",
        "validation": {"min": 1, "max": 500},
    },
    # ------------------------------------------------------------------
    # database  (source: app/db/database.py)
    # ------------------------------------------------------------------
    {
        "key": "database.retention_days",
        "category": "database",
        "subcategory": None,
        "value": 90,
        "type": "int",
        "display_name": "Check Results Retention (days)",
        "description": "Keep check results for this many days before deletion. Older data is automatically removed.",
        "validation": {"min": 7, "max": 3650},
    },
    {
        "key": "database.compress_after_days",
        "category": "database",
        "subcategory": None,
        "value": 7,
        "type": "int",
        "display_name": "Compress After (days)",
        "description": "Compress check results older than this many days. Compression saves 80-90% space.",
        "validation": {"min": 1, "max": 365},
    },
    {
        "key": "database.artifacts_retention_days",
        "category": "database",
        "subcategory": None,
        "value": 30,
        "type": "int",
        "display_name": "Artifacts Retention (days)",
        "description": "Keep check artifacts (screenshots, logs) for this many days before deletion.",
        "validation": {"min": 1, "max": 365},
    },
    {
        "key": "database.hourly_aggregate_retention_days",
        "category": "database",
        "subcategory": None,
        "value": 365,
        "type": "int",
        "display_name": "Hourly Aggregates Retention (days)",
        "description": "Keep hourly aggregated metrics for this many days (1 year default).",
        "validation": {"min": 30, "max": 1825},
    },
    {
        "key": "database.daily_aggregate_retention_days",
        "category": "database",
        "subcategory": None,
        "value": 1825,
        "type": "int",
        "display_name": "Daily Aggregates Retention (days)",
        "description": "Keep daily aggregated metrics for this many days (5 years default).",
        "validation": {"min": 90, "max": 3650},
    },
    # ------------------------------------------------------------------
    # security  (source: settings_core_service.ensure_security_defaults)
    # NOTE: the 3 dead keys that only database.py defined are intentionally
    # dropped: security.session_timeout_minutes, security.max_login_attempts,
    # security.lockout_duration_minutes.
    # ------------------------------------------------------------------
    # Session & Authentication
    {
        "key": "security.session_lifetime_days",
        "category": "security",
        "subcategory": "Session & Authentication",
        "value": 7,
        "type": "int",
        "display_name": "Session Lifetime (days)",
        "description": "How long users stay logged in before requiring re-authentication",
        "validation": {"min": 1, "max": 90},
    },
    {
        "key": "security.max_failed_attempts",
        "category": "security",
        "subcategory": "Session & Authentication",
        "value": 5,
        "type": "int",
        "display_name": "Maximum Failed Login Attempts",
        "description": "Number of failed login attempts before account locks",
        "validation": {"min": 3, "max": 10},
    },
    {
        "key": "security.account_lock_duration_minutes",
        "category": "security",
        "subcategory": "Session & Authentication",
        "value": 30,
        "type": "int",
        "display_name": "Account Lock Duration (minutes)",
        "description": "How long accounts remain locked after too many failed attempts",
        "validation": {"min": 5, "max": 1440},
    },
    # Rate Limiting
    {
        "key": "security.rate_limit_enabled",
        "category": "security",
        "subcategory": "Rate Limiting",
        "value": True,
        "type": "bool",
        "display_name": "Enable Rate Limiting",
        "description": "Enable rate limiting on authentication endpoints to prevent brute-force attacks",
        "validation": None,
    },
    {
        "key": "security.login_rate_limit",
        "category": "security",
        "subcategory": "Rate Limiting",
        "value": "10/15minutes",
        "type": "string",
        "display_name": "Login Rate Limit",
        "description": "Rate limit for login attempts per IP address (format: count/period, e.g., '10/15minutes')",
        "validation": None,
    },
    {
        "key": "security.api_rate_limit",
        "category": "security",
        "subcategory": "Rate Limiting",
        "value": "100/minute",
        "type": "string",
        "display_name": "API Rate Limit",
        "description": "Rate limit for general API requests per IP address (format: count/period, e.g., '100/minute')",
        "validation": None,
    },
    {
        "key": "security.registration_rate_limit",
        "category": "security",
        "subcategory": "Rate Limiting",
        "value": "5/hour",
        "type": "string",
        "display_name": "Agent Registration Rate Limit",
        "description": "Rate limit for agent registration per IP address (format: count/period, e.g., '5/hour')",
        "validation": None,
    },
    # Password Complexity
    {
        "key": "security.min_password_length",
        "category": "security",
        "subcategory": "Password Complexity",
        "value": 8,
        "type": "int",
        "display_name": "Minimum Password Length",
        "description": "Minimum number of characters required for passwords",
        "validation": {"min": 6, "max": 32},
    },
    {
        "key": "security.require_uppercase",
        "category": "security",
        "subcategory": "Password Complexity",
        "value": True,
        "type": "bool",
        "display_name": "Require Uppercase Letter",
        "description": "Require at least one uppercase letter in passwords",
        "validation": None,
    },
    {
        "key": "security.require_lowercase",
        "category": "security",
        "subcategory": "Password Complexity",
        "value": True,
        "type": "bool",
        "display_name": "Require Lowercase Letter",
        "description": "Require at least one lowercase letter in passwords",
        "validation": None,
    },
    {
        "key": "security.require_number",
        "category": "security",
        "subcategory": "Password Complexity",
        "value": True,
        "type": "bool",
        "display_name": "Require Number",
        "description": "Require at least one digit in passwords",
        "validation": None,
    },
    {
        "key": "security.require_special_char",
        "category": "security",
        "subcategory": "Password Complexity",
        "value": False,
        "type": "bool",
        "display_name": "Require Special Character",
        "description": "Require at least one special character (!@#$%^&*()_+-=[]{}|;:,.<>?) in passwords",
        "validation": None,
    },
    {
        "key": "security.check_common_passwords",
        "category": "security",
        "subcategory": "Password Complexity",
        "value": True,
        "type": "bool",
        "display_name": "Check Against Common Passwords",
        "description": "Reject passwords that appear in common password lists",
        "validation": None,
    },
    # Network Protection (SSRF)
    {
        "key": "security.block_cloud_metadata",
        "category": "security",
        "subcategory": "Network Protection",
        "value": True,
        "type": "bool",
        "display_name": "Block Cloud Metadata Endpoints",
        "description": "Block checks from targeting cloud metadata and link-local addresses (169.254.x.x). Prevents metadata exfiltration in cloud/container environments.",
        "validation": None,
    },
    {
        "key": "security.block_private_networks",
        "category": "security",
        "subcategory": "Network Protection",
        "value": False,
        "type": "bool",
        "display_name": "Block Private Network Targets",
        "description": "Block checks from targeting RFC 1918 private networks (10.x, 172.16-31.x, 192.168.x). Disabled by default since most self-hosted users monitor internal services.",
        "validation": None,
    },
    # ------------------------------------------------------------------
    # general  (union of both sources, reconciled to the correct scheme)
    # ------------------------------------------------------------------
    {
        "key": "general.timezone",
        "category": "general",
        "subcategory": None,
        "value": "UTC",
        "type": "string",
        "display_name": "Default Timezone",
        "description": "Default timezone for displaying dates and times across the application.",
        "validation": {
            "enum": [
                "UTC",
                "America/New_York",
                "America/Chicago",
                "America/Denver",
                "America/Los_Angeles",
                "America/Phoenix",
                "America/Anchorage",
                "Pacific/Honolulu",
                "Europe/London",
                "Europe/Paris",
                "Europe/Berlin",
                "Asia/Tokyo",
                "Asia/Shanghai",
                "Australia/Sydney",
            ]
        },
    },
    {
        "key": "general.date_format",
        "category": "general",
        "subcategory": None,
        "value": "long",
        "type": "string",
        "display_name": "Date Format",
        "description": "How dates are displayed (long: November 8, 2025 / short: 11/8/2025 / iso: 2025-11-08)",
        "validation": {"enum": ["long", "short", "iso"]},
    },
    {
        "key": "general.time_format",
        "category": "general",
        "subcategory": None,
        "value": "24h",
        "type": "string",
        "display_name": "Time Format",
        "description": "Format for displaying times.",
        "validation": {"enum": ["24h", "12h"]},
    },
    {
        "key": "general.default_page_size",
        "category": "general",
        "subcategory": None,
        "value": 50,
        "type": "int",
        "display_name": "Default Page Size",
        "description": "Default number of items to show per page in lists and tables.",
        "validation": {"enum": [10, 25, 50, 100, 200]},
    },
    {
        "key": "general.dashboard_refresh_interval",
        "category": "general",
        "subcategory": None,
        "value": 10,
        "type": "int",
        "display_name": "Dashboard Auto-Refresh Interval (seconds)",
        "description": "How often the status dashboard automatically refreshes",
        "validation": {"min": 5, "max": 300},
    },
    {
        "key": "general.default_chart_time_range",
        "category": "general",
        "subcategory": None,
        "value": "4h",
        "type": "string",
        "display_name": "Default Chart Time Range",
        "description": "Default time range for performance charts",
        "validation": {"enum": ["1h", "4h", "8h", "12h", "24h", "3d", "7d"]},
    },
    {
        "key": "general.agent_stale_threshold_seconds",
        "category": "general",
        "subcategory": None,
        "value": 300,
        "type": "int",
        "display_name": "Agent Stale Threshold (seconds)",
        "description": "Highlight agents in yellow if not seen for this many seconds",
        "validation": {"min": 60, "max": 3600},
    },
    # ------------------------------------------------------------------
    # metrics  (source: settings_core_service.ensure_metrics_defaults)
    # ------------------------------------------------------------------
    {
        "key": "metrics.enabled",
        "category": "metrics",
        "subcategory": None,
        "value": True,
        "type": "bool",
        "display_name": "Enable Metrics Endpoint",
        "description": "Enable or disable the /metrics endpoint entirely",
        "validation": None,
    },
    {
        "key": "metrics.auth_required",
        "category": "metrics",
        "subcategory": None,
        "value": False,
        "type": "bool",
        "display_name": "Require Authentication",
        "description": "Require bearer token authentication for /metrics endpoint (default: public for Prometheus)",
        "validation": None,
    },
    {
        "key": "metrics.bearer_token",
        "category": "metrics",
        "subcategory": None,
        "value": "",
        "type": "string",
        "display_name": "Bearer Token",
        "description": "Dedicated bearer token for Prometheus scraping (leave empty to use API tokens)",
        "validation": None,
    },
    {
        "key": "metrics.agent_timeout_seconds",
        "category": "metrics",
        "subcategory": None,
        "value": 300,
        "type": "int",
        "display_name": "Agent Timeout (seconds)",
        "description": "Seconds without heartbeat before agent is marked as down in luxswirl_agent_up metric",
        "validation": {"min": 30, "max": 3600},
    },
]
